module.exports = {
  descLst: [
    "It caught him off guard that space smelled of seared steak.",
    "The Japanese yen for commerce is still well-known.",
    "Sarah ran from the serial killer holding a jug of milk.",
    "He found the chocolate covered roaches quite tasty.",
    "Love is not like pizza.",
    "Theyre playing the piano while flying in the plane.",
    "I liked their first two albums but changed my mind after that charity gig.",
    "She was too busy always talking about what she wanted to do to actually do any of it.",
    "The pet shop stocks everything you need to keep your anaconda happy.",
    "The efficiency with which he paired the socks in the drawer was quite admirable.",
    "I am happy to take your donation; any amount will be greatly appreciated.",
    "The two walked down the slot canyon oblivious to the sound of thunder in the distance.",
    "We need to rent a room for our party.",
    "It was obvious she was hot, sweaty, and tired.",
    "At last",
    "Facing his greatest fear, he ate his first marshmallow.",
    "He felt that dining on the bridge brought romance to his relationship with his cat.",
    "A quiet house is nice until you are ordered to stay in it for months.",
    "Traveling became almost extinct during the pandemic.",
    "One small action would change her life, but whether it would be for better or for worse was yet to be determined.",
    "She always speaks to him in a loud voice.",
    "The glacier came alive as the climbers hiked closer.",
    "I often see the time 11:11 or 12:34 on clocks.",
    "Nobody has encountered an explosive daisy and lived to tell the tale.",
    "When motorists sped in and out of traffic, all she could think of was those in need of a transplant.",
    "The father died during childbirth.",
    "He dreamed of leaving his law firm to open a portable dog wash.",
    "With a single flip of the coin, his life changed forever.",
    "Trash covered the landscape like sprinkles do a birthday cake.",
    "Her hair was windswept as she rode in the black convertible.",
    "Cats are good pets, for they are clean and are not noisy.",
  ],
};
