module.exports = {
  nomesLst: [
    "Sra. Lara Alves",
    "Giovanna Cardoso",
    "Sophie Oliveira",
    "Pietra Ferreira",
    "Enzo da Conceição",
    "Eduardo Alves",
    "Pedro Henrique Moreira",
    "Diogo Rodrigues",
    "Juan Porto",
    "Luiz Gustavo Ribeiro",
    "Benjamin Pinto",
    "Sra. Alexia Carvalho",
    "Juan Porto",
    "Rafaela Peixoto",
    "Rebeca Gonçalves",
    "Fernando Lopes",
    "Srta. Maria Cavalcanti",
    "Emanuelly Fogaça",
    "Dra. Ana Sales",
    "Dr. Rodrigo Monteiro",
    "Ana Ribeiro",
    "Srta. Mariana Santos",
    "Sabrina Lopes",
    "Bernardo Nunes",
    "Raul Silva",
    "Nicolas da Cunha",
    "Erick da Cruz",
    "Yago Ferreira",
    "Vinicius Cardoso",
    "Camila Nascimento",
    "Benjamin Souza",
    "Kaique Freitas",
    "Elisa Carvalho",
    "Leandro Porto",
    "Pedro Henrique Nunes",
    "Isadora Cardoso",
    "Dra. Helena Campos",
    "Dra. Clarice Nascimento",
    "Caio Moura",
    "João Santos",
    "Dr. Benício Nunes",
    "Valentina Alves",
    "Maria Vitória Sales",
    "Carolina Martins",
    "Gustavo Fogaça",
    "Sr. Lorenzo Barbosa",
    "Pedro Henrique da Conceição",
    "Isabel Santos",
    "Ana Vieira",
    "Lucas Gabriel Pereira",
    "Laura Ribeiro",
    "Sophia da Rocha",
    "Daniela Peixoto",
    "Mariana Cavalcanti",
    "Lucas Santos",
    "Ryan Barros",
    "Cecília da Rocha",
    "Pietra Oliveira",
    "Beatriz Carvalho",
    "João Vitor Rodrigues",
    "Clara Oliveira",
    "João Guilherme Nascimento",
    "Lara Castro",
    "Srta. Heloísa da Cruz",
    "João Miguel Nascimento",
    "Heitor Duarte",
    "Dra. Caroline Santos",
    "Ian Moura",
    "Arthur Dias",
    "Gustavo Lopes",
    "Luiz Otávio da Cunha",
    "Dr. Nathan da Mota",
    "Ryan Fogaça",
    "Gabriel das Neves",
    "Emilly da Rosa",
    "Raul Farias",
    "Sarah Cardoso",
    "Rafael Nunes",
    "João Pedro Ribeiro",
    "Kevin da Costa",
    "Yuri Moreira",
    "Gabrielly Fogaça",
    "Raquel Lopes",
    "Laura Barros",
    "Kamilly Correia",
    "Dr. Bruno Vieira",
    "Luiza Monteiro",
    "Dr. Lorenzo Fogaça",
    "Thales Duarte",
    "Maria Alice Pereira",
    "Rodrigo Araújo",
    "Sra. Ana Laura Campos",
    "Ryan Gomes",
    "Levi Almeida",
    "Dr. Carlos Eduardo Gonçalves",
    "Olivia Moraes",
    "Noah Novaes",
    "Dra. Pietra Cardoso",
    "Benício Barbosa",
    "Vitor Farias",
  ],
};
